spring.application.name=basic-mongo

# local MongoDB
spring.mongodb.uri=mongodb://localhost:27017/studentsdb
# optional: server.port=8081

#for mongoDB Atlas
#spring.mongodb.uri=mongodb+srv://<username>:<pwd>@<cluster>.mongodb.net/mygrocerylist
#spring.mongodb.database=mygrocerylist
