spring.application.name=basic-mongo

# local MongoDB
#spring.mongodb.uri=mongodb://localhost:27017/studentsdb

# use mongo docker
#spring.mongodb.uri=mongodb://root:root@localhost:27018/studentsdb?authSource=admin
spring.mongodb.host=localhost
spring.mongodb.port=27018
spring.mongodb.database=studentsdb
spring.mongodb.username=root
spring.mongodb.password=root
spring.mongodb.authentication-database=admin


#for mongoDB Atlas
#spring.mongodb.uri=mongodb+srv://<username>:<pwd>@<cluster>.mongodb.net/mygrocerylist
#spring.mongodb.database=mygrocerylist
